config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: {
    sessions:      'backend/devise/sessions',
    passwords:     'backend/devise/passwords',
    confirmations: 'backend/devise/confirmations',
    registrations: 'backend/devise/registrations',
  }

  devise_scope :user do
    get  '/sign_in', to: 'backend/devise/sessions#new',      as: 'sign_in'
    get  '/sign_up', to: 'backend/devise/registrations#new', as: 'sign_up'
  end

  scope module: :frontend do
    root to: 'webs#index'

    get '/maps/:map_id/dots', to: 'webs#dots', as: :front_map_dots
  end

  scope "/admin", module: :backend do
    get '/', to: 'maps#index'

    resources :maps do
      resources :upload_maps, only: [:new, :create]
      resources :dots
    end
  end

end

app/controllers/frontend/webs_controller.rb
class Frontend::WebsController < ApplicationController

  def index
    @maps = Map.all
  end

  def dots
    @map  = Map.find(params[:map_id])
    @dots = @map.dots.includes(:user, :map).all

    render 'frontend/webs/index.kml.builder'
  end

end

app/helpers/frontend/webs_helper.rb
module Frontend::WebsHelper
end

app/views/frontend/webs/index.html.slim
.table-responsive
  table.table.table-striped
    thead
      tr
        th 地圖名稱
        th colspan="3" Actions
    tbody
      - @maps.each do |map|
        tr
          td = map.title
          td.actions
            = link_to 'KML', front_map_dots_path(map, format: :kml)
            / = link_to 'CSV', front_map_dots_path(map, format: :csv)
            = link_to 'URL', front_map_dots_url(map, format: :kml), class: 'copy'