config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: {
    sessions:      'backend/devise/sessions',
    passwords:     'backend/devise/passwords',
    confirmations: 'backend/devise/confirmations',
    registrations: 'backend/devise/registrations',
  }

  devise_scope :user do
    get  '/sign_in', to: 'backend/devise/sessions#new',      as: 'sign_in'
    get  '/sign_up', to: 'backend/devise/registrations#new', as: 'sign_up'
  end

  scope module: :frontend do
    root to: 'webs#index'

    get '/maps/:map_id/dots', to: 'webs#dots', as: :front_map_dots
  end

  scope "/admin", module: :backend do
    get '/', to: 'maps#index'

    resources :maps do
      resources :upload_maps, only: [:new, :create]
      resources :dots
    end
  end

end

app/views/layouts/_nav.html.slim
nav.navbar.navbar-fixed-top.navbar-dark.bg-inverse
  button.navbar-toggler.hidden-sm-up aria-controls="navbar-header" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbar-header" data-toggle="collapse" type="button"

  #navbar-header.collapse.navbar-toggleable-xs
    a.navbar-brand href="/"  Map Merge

    ul.nav.navbar-nav
      = nav_link '首頁', root_path, icon: 'fa fa-home'
      - if current_user
        = nav_link '後台', '/admin', icon: 'fa fa-pencil'
      - unless current_user
        li.nav-item
          = link_to sign_up_path, class: 'nav-link' do
            i.fa.fa-user aria-hidden="true"
            | 註冊
        li.nav-item
          = link_to sign_in_path, class: 'nav-link' do
            i.fa.fa-sign-in aria-hidden="true"
            | 登入
      - else
        li.nav-item
          = link_to destroy_user_session_path, class: 'nav-link', data: { method: "delete" } do
            i.fa.fa-sign-out aria-hidden="true"
            | 登出

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title MapMerge
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    #wrap
      = render 'layouts/nav'

      .container.bottom-buffer
        = content_tag(:div, flash[:notice].html_safe,  class: "alert alert-info")    if flash[:notice].present?
        = content_tag(:div, flash[:success].html_safe, class: "alert alert-success") if flash[:success].present?
        = content_tag(:div, flash[:warning].html_safe, class: "alert alert-warning") if flash[:warning].present?
        = content_tag(:div, flash[:error].html_safe,   class: "alert alert-danger")  if flash[:error].present?

        = yield

      #push

    #footer
      .container
        .credit Copyright © 2016 frsnic.